I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 66, in script
    jump shell_intro_bad
ScriptError: could not find label 'shell_intro_bad'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 66, in script
    jump shell_intro_bad
  File "C:\Users\sanja\Documents\renpy-7.4.11-sdk/renpy/ast.py", line 1757, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\sanja\Documents\renpy-7.4.11-sdk/renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'shell_intro_bad'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
HeartInCode 1.0
Tue Jan 18 16:58:06 2022
